# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm, arm64]
        exclude:
          - goos: darwin
            goarch: arm
          - goos: darwin
            goarch: "386"
      fail-fast: true
    steps:
    - uses: actions/checkout@v3

    - name: 设置go环境
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: 安装protoc
      run: make build_protoc
    - name: 准备安装工具
      run: make dev_tool
      
    - name: 生成natsrpc协议
      run: make gen_natsrpc
    - name: 生成客户端协议
      run: make gen_proto
      
    - name: 编译二进制文件
      run: make build
      
    - name: 上传二进制
      uses: actions/upload-artifact@v3.1.2
      with:
           name: ${{ matrix.goos }}_${{ matrix.goarch }}
           path: bin/
